### ISSUE TITLE
Heads up: gnus-last-element will (eventually) go away

### ISSUE THREAD

**Issue by girzel** [wavexx/gnus-desktop-notify.el#11]
Hi, it's likely that the function `gnus-last-element' will go away at  some point; I see you've got a call to that in your code. Obviously this won't be an issue for quite a while, but you might as well replace it with (car (last ...)), which is more efficient anyway.

https://debbugs.gnu.org/cgi/bugreport.cgi?bug=28856

**Comment by wavexx** [comment]
Thanks for the heads-up. But.. question: did you do a code search on github to find all usage instances?

**Comment by girzel** [comment]
I didn't look at all 56 pages, as they mostly seemed to be clones the gnus repository itself! But yes, I've contacted the few external packages that are using the function.

**Comment by basil-conto** [comment]
I actually happened across https://lists.gnu.org/archive/html/bug-gnu-emacs/2017-10/msg00987.html completely by chance just now, which is what prompted me to push the fix. I was wondering when Eric would raise the issue here, until I noticed I wasn't "watching" this GitHub project, so I never received notification...
